### ISSUE TITLE
fmt.Errorf format verbs missing

### ISSUE THREAD

**Issue by disintegration** [aerofs/lipwig#1]
Hi, 
I think the format 'verbs' (eg %s, %d) are missing here:

https://github.com/aerofs/lipwig/blob/b80222b801e3a3e173e12619c81a073c9c3eed09/server/connection.go#L159
https://github.com/aerofs/lipwig/blob/b80222b801e3a3e173e12619c81a073c9c3eed09/server/connection.go#L163

**Comment by huguesb** [comment]
Good catch! Fixed in https://github.com/aerofs/lipwig/commit/6636117f800a3815a8ad34efcde62c20f309a8ed
